server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

app:
  mail:
    from: todo@localhost
    base-url: http://prod.server.url
